<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-04-29 11:41

$extensionPath = t3lib_extMgm::extPath('stylestoinline');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_stylestoinline_viewhelpers_stylestoinlineviewhelper' => $extensionClassesPath . 'ViewHelpers/StylesToInlineViewHelper.php',
);
?>